version: '2'
services:
    jhrect20182009-app:
        image: jhrect20182009
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://jhrect20182009-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=jhrect20182009
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhrect20182009-mongodb:
        extends:
            file: mongodb.yml
            service: jhrect20182009-mongodb
