version: '2'
services:
    jhrect20182009-mongodb:
        image: mongo:3.6.3
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/jhrect20182009/mongodb/:/data/db/
